apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmasa-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: cloudmasa-client
  template:
    metadata:
      labels:
        app: cloudmasa-client
    spec:
      containers:
        - name: client
          image: {{ .Values.client.image }}
          ports:
            - containerPort: {{ .Values.client.port }}
