apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmasa-server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: cloudmasa-server
  template:
    metadata:
      labels:
        app: cloudmasa-server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - secretRef:
                name: server-env
