replicaCount: 2

image:
  server:
    repository: vigneshkavi/cloudmasa-server
    tag: v0.0
  client:
    repository: vigneshkavi/cloudmasa-client
    tag: v0.0

service:
  server:
    port: 3000
  client:
    port: 80

env:
  MONGO_URI: "mongodb+srv://keerthisankavi_db_user:mfNxw8wDf5Q1nVjZ@cluster.xmlrcxf.mongodb.net/?retryWrites=true&w=majority&appName=cluster"
  NODE_ENV: production

ingress:
  enabled: true
  className: nginx
  host: app.cloudmasa.com
